### ISSUE TITLE
Transfer this App to brainlife/ org

### ISSUE THREAD

**Issue by soichih** [davhunt/app-snr_in_cc#15]
Hello @davhunt ! I hope things are going well. @bacaron and I'd like to make some changes to this App, but we weren't sure if you are still around / have time to work on this App. Do you think it's possible to transfer ownership of this App /brainlife org so we can maintain it communally?

**Comment by davhunt** [comment]
Hi @soichih I'm good, thanks! Um sure, I think when I last tried to do this I wasn't able to, do I need to be a member of the github or something? Yes I should be able to help maintain this.

**Comment by davhunt** [comment]
Yeah when I try it says "You don't have permission to create public repositories on brainlife" @soichih @bacaron

**Comment by soichih** [comment]
I've sent you an invite to be a member of "App Maintainers" team on
brainlife org. Can you accept the invite and try again?

**Comment by davhunt** [comment]
Thanks! Should be transferred now
